# site properties and page defaults
title: MARIA
subtitle: Marymount Applied Research in Artificial Intelligence
description: Marymount's research lab for all things AI, ML, NLP and Dats Science
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
#  email: nathan.green@marymount.edu
#  orcid: 0000-0001-8713-9213
#  google-scholar: ETJoidYAAAAJ
#  github: MarymountUniversity
#  twitter: MarymountUniversity
#  youtube: MarymountUniversity

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
