- id: "issn:1937-4771"
  title: Sentiment and Topic Modeling Analysis of Reddit Posts on Changing One's Major
  authors:
    - Nathan Green
    - Karen Works
  publisher: Consortium for Computing Sciences in Colleges
  date: 2023-11-01
  container-title: Journal of Computing Sciences in Colleges
  volume: 39
  issue: 5
  pages: 13-22
  address: Evansville, IN, USA
  type: article-journal
