- id: custom:green2010packplay
  type: paper
  title: 'Packplay: Mining semantic data in collaborative games'
  authors:
  - Green, Nathan
  - Breimyer, Paul
  - Kumar, Vinay
  - Samatova, Nagiza
  date: '2010'
  pages: 227--234
- id: custom:green2011effects
  type: paper
  title: Effects of noun phrase bracketing in dependency parsing and machine translation
  authors:
  - Green, Nathan
  date: '2011'
  pages: 69--74
- id: custom:popel2011influence
  type: paper
  title: Influence of Parser Choice on Dependency-Based MT
  authors:
  - Popel, Martin
  - Marecek, David
  - Green, Nathan
  date: '2011'
  pages: 433--439
- id: custom:green2004reduced
  type: paper
  title: A reduced QWERTY keyboard for mobile text entry
  authors:
  - Green, Nathan
  - Kruger, Jan
  - Faldu, Chirag
  - St. Amant, Robert
  date: '2004'
  pages: 1429--1432
- id: custom:green2011dependency
  type: journal
  title: Dependency Parsing
  authors:
  - Green, Nathan David
  container-title: WDS '11
  date: '2011'
  issue: Proceedings of Contributed Papers
  pages: 137--142
- id: custom:green2012hybrid
  type: paper
  title: Hybrid Combination of Constituency and Dependency Trees into an Ensemble
    Dependency Parser
  authors:
  - Green, Nathan
  - '{\v{Z}}abokrtsk{\`y}, Zden{\v{e}}k'
  date: '2012'
  pages: 19--26
- id: custom:green2012using
  type: paper
  title: Using an SVM Ensemble System for Improved Tamil Dependency Parsing
  authors:
  - Green, Nathan
  - Ramasamy, Loganathan
  - '{\v{Z}}abokrtsk{\`y}, Zden{\v{e}}k'
  date: '2012'
  pages: 72--77
- id: custom:green2012indonesian
  type: paper
  title: 'Indonesian dependency treebank: Annotation and parsing'
  authors:
  - Green, Nathan
  - Larasati, Septina Dian
  - Zabokrtsky, Zdenek
  date: '2012'
  pages: 137--145
- id: custom:chakraborty2013link
  type: journal
  title: Link analysis
  authors:
  - Chakraborty, Arpan
  - Wilson, Kevin
  - Green, Nathan
  - Alur, Shravan Kumar
  - Ergin, Fatih
  - Gurumurthy, Karthik
  - Manzano, Romulo
  - Chinta, Deepti
  container-title: Practical graph mining with R
  date: '2013'
  publisher: Chapman \& Hall Boca Raton, FL
  pages: '75'
- id: custom:green2018first
  type: paper
  title: 'The First 100 Days: A Corpus Of Political Agendas on Twitter'
  authors:
  - Green, Nathan
  - Larasati, Septina
  date: '2018'
- id: custom:costa2016hybrid
  type: preprint
  title: Hybrid approaches to machine translation
  authors:
  - Costa-juss{\`a}, Marta R
  - Rapp, Reinhard
  - Lambert, Patrik
  - Eberle, Kurt
  - Banchs, Rafael E
  - Babych, Bogdan
  date: '2016'
  publisher: Springer International Publishing
- id: custom:green2019revisiting
  type: journal
  title: 'Revisiting an educator''s dilemma: using natural language processing to
    analyze the needs of employers and inform curriculum development'
  authors:
  - Green, Nathan
  - Liu, Xiang
  - Murphy, Diane
  container-title: Journal of Computing Sciences in Colleges
  date: '2019'
  publisher: Consortium for Computing Sciences in Colleges
  volume: '34'
  issue: '3'
  pages: 97--107
- id: custom:green2012hybrid
  type: paper
  title: Hybrid combination of constituency and dependency trees into an ensemble
    dependency parser
  authors:
  - Green, Nathan
  - ˇZabokrtsk{\`y}, Zdenek
  date: '2012'
  pages: 19--26
- id: custom:green2020using
  type: journal
  title: Using an Electronic Resume Analyzer Portal (eRAP) to Improve College Graduates
    Employability.
  authors:
  - Green, Nathan
  - Liu, Michelle
  - Murphy, Diane
  container-title: Information Systems Education Journal
  date: '2020'
  publisher: Information Systems and Computing Academic Professionals. Box 488~…
  volume: '18'
  issue: '3'
  pages: 28--37
- id: custom:alshameri2020analyzing
  type: journal
  title: Analyzing the strength between mission and vision statements and industry
    via machine learning
  authors:
  - Alshameri, Faleh
  - Green, Nathan
  container-title: Journal of Applied Business Research (JABR)
  date: '2020'
  volume: '36'
  issue: '3'
  pages: 121--128
- id: custom:green2009webbanc
  type: paper
  title: 'Webbanc: building semantically-rich annotated corpora from web user annotations
    of minority languages'
  authors:
  - Green, Nathan
  - Breimyer, Paul
  - Kumar, Vinay
  - Samatova, Nagiza
  date: '2009'
  pages: 48--56
- id: custom:green2022measuring
  type: paper
  title: Measuring Users' Attitudinal and Behavioral Responses to Persuasive Communication
    Techniques in Human Robot Interaction
  authors:
  - Green, Nathan
  - Works, Karen
  date: '2022'
  pages: 778--782
- id: custom:green2022defining
  type: paper
  title: Defining the Metaverse through the lens of academic scholarship, news articles,
    and social media
  authors:
  - Green, Nathan
  - Works, Karen
  date: '2022'
  pages: 1--5
- id: custom:liu2023hunt
  type: journal
  title: 'The hunt for cybersecurity data: Exploring the availability of open datasets
    for cybersecurity scientific research'
  authors:
  - Liu, Michelle
  - Murphy, Diane
  - Green, Nathan
  container-title: Journal of Computing Sciences in Colleges
  date: '2023'
  publisher: Consortium for Computing Sciences in Colleges
  volume: '39'
  issue: '3'
  pages: 171--181
